language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t briankiernan/ci-cd-cra-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true briankiernan/ci-cd-cra-aws npm run test
